config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :softwares do
    resources :licenses, only: %i[new create]
  end

  resources :licenses do
    resources :reviews, only: %i[new create]
  end

  resources :my_licenses, only: %i[index edit update]

  get 'my_profile', to: 'pages#profile'

  resources :my_softwares
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 border-top bg-dark">
  <div class="col-md-4 d-flex align-items-center">
    <%= link_to root_path, class: "mb-3 me-2 ms-2 mb-md-0 text-body-secondary text-decoration-none lh-1" do %>
      <%= image_tag("logos/logo_stacky.png", alt: "Stacky", width: "50", class: "ms-3") %>
    <% end %>
    <span class="mb-3 mb-md-0 text-light">© 2025 Company, Inc</span>
  </div>

  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex me-4">
    <li class="ms-3"><a class="text-white" href="#"><i class="fa-brands fa-x-twitter"></i></a></li>
    <li class="ms-3"><a class="text-white" href="#"><i class="fa-brands fa-instagram"></i></a></li>
    <li class="ms-3"><a class="text-white" href="#"><i class="fa-brands fa-facebook"></i></a></li>
  </ul>
</footer>

app/views/shared/_generic_soft_card.html.erb
<div class="col-md-4 p-2">
  <%= link_to software_path(software), class: "text-decoration-none text-dark" do %>
    <div class="app-card mb-3 shadow-sm hover-shadow-lg transition-all" style="max-width: 540px; height: 280px; border-radius: 15px; overflow: hidden;">
      <div class="row g-0 h-100">
        <!-- Left Column: Logo and Tags -->
        <div class="col-md-4 d-flex flex-column justify-content-between align-items-center p-3" style="background-color: #f8f9fa;">
          <% if software.logo.attached? %>
            <%= cl_image_tag software.logo.key, transformation: [{ crop: "lfill", width: 110, height: 110, quality: "auto", fetch_format: "auto"},  {radius: 10}], class: "img-fluid rounded-circle shadow-sm mb-3" %>
          <% else %>
            <%= image_tag "logos/default-logo.jpg", class: "img-fluid rounded-circle shadow-sm mb-3" %>
          <% end %>

          <div class="tag-section text-center">
            <% if software.team_tags.any? %>
              <% software.team_tags.each do |tag| %>
                <% if tag.name.present? %>
                  <div class="tag team-tag mb-2 bg-light rounded-pill shadow-sm">
                    <p class="px-3 py-1 m-0 small fw-bold"> <%= truncate(tag.name, length: 17, omission: '...') %> </p>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <p class="px-3 py-1 m-0 small text-muted">No tags</p>
            <% end %>
          </div>
        </div>

        <!-- Right Column: Content -->
        <div class="col-md-8 d-flex flex-column justify-content-between p-3" style="background-color: #ffffff;">
          <div>
            <div class="border-bottom mb-2">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h5 class="card-title mb-0 fw-bold">
                  <%= software.name %>
                </h5>
                <% if software.average_rating.present? %>
                  <span class="badge bg-info text-dark fs-6">
                    <%= software.average_rating %>
                    <i class="fa-solid fa-star"></i>
                  </span>
                <% else %>
                  <span class="badge bg-secondary fs-6">No ratings</span>
                <% end %>
              </div>

            </div>

            <p class="card-text text-muted mb-3"><%= truncate(software.description, length: 80, omission: '...') %></p>
          </div>

          <div>
            <% if software.category_tags.any? %>
              <div class="tag <%= software.category_tags.first.color %> me-2 mb-2 d-inline-block rounded-pill shadow-sm">
                <p class="px-3 py-1 m-0 small fw-bold"> <%= software.category_tags.first.name %> </p>
              </div>
            <% else %>
              <p class="text-muted small mb-2">No category</p>
            <% end %>

            <p class="card-text mb-0 fw-bold">
              <span class="text-success"><%= software.price_month.presence || "Free" %></span>
              <span class="text-muted small">/month</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-dark sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand text-white ms-3" do %>
      <%= image_tag("logos/logo_stacky.png", alt: "Stacky", width: "50") %> Stacky
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= form_with(url: softwares_path, method: :get, local: true, class: "d-flex w-25", role: "search") do |form| %>
      <%= form.text_field :query, class: "form-control me-2", placeholder: "Search a software...", aria_label: "Search" %>
      <%= form.submit "Search", class: "btn btn-outline-success" %>
    <% end %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent" data-controller="navbar-toggler">
        <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active" data-navbar-toggler-target="userLi">
            <%= link_to "Marketplace", softwares_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item active" data-navbar-toggler-target="userLi">
            <%= link_to "My licenses", my_licenses_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item" data-navbar-toggler-target="ownerLi">
            <%= link_to "My softwares", my_softwares_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item d-flex align-items-center px-3 text-white rounded me-2" style="width: 120px; display: flex; justify-content: space-between;">
            <div class="form-check form-switch d-flex align-items-center" data-navbar-toggler-target="toggle">
              <input class="form-check-input me-2" type="checkbox" role="switch" id="flexSwitchCheckDefault" style="transform: scale(1.2);" data-action="change->navbar-toggler#switch" <%= session[:mode] == "owner" ? "checked": "" %>>
              <label class="form-check-label ms-2" for="flexSwitchCheckDefault"><%= session[:mode] %></label>
            </div>
          </li>
        <% else %>
          <li class="nav-item me-3">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
          <li class="nav-item dropdown me-3">
            <% if user_signed_in? %>
              <%= image_tag("avatars/Kermit.JPG", width:"40", class: "dropdown-toggle rounded-circle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }) %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My profile", my_profile_path, class: "dropdown-item" %>
                <a class="dropdown-item" href="#">Preferences</a>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item" %>
              </div>
            <% else %>
              <%= image_tag("avatars/default-pp.jpg", width:"40", class: "dropdown-toggle rounded-circle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }) %>
            <% end %>
          </li>
        </ul>
    </div>
  </div>
</div>

app/views/shared/_test_card.html.erb
<div class="col-md-4 p-2">
  <%= link_to software_path(software), class: "text-decoration-none text-dark" do %>
    <div class="app-card mb-3 shadow-sm hover-shadow-lg transition-all" style="max-width: 540px; height: 280px; border-radius: 15px; overflow: hidden;">
      <div class="row g-0 h-100">
        <!-- Left Column: Logo and Tags -->
        <div class="col-md-4 d-flex flex-column justify-content-between align-items-center p-3" style="background-color: #f8f9fa;">
          <% if software.logo.attached? %>
            <%= cl_image_tag software.logo.key, transformation: [{ crop: "lfill", width: 110, height: 110, quality: "auto", fetch_format: "auto"},  {radius: 10}], class: "img-fluid rounded-circle shadow-sm mb-3" %>
          <% else %>
            <%= image_tag "logos/default-logo.jpg", class: "img-fluid rounded-circle shadow-sm mb-3" %>
          <% end %>

          <div class="tag-section text-center">
            <% if software.team_tags.any? %>
              <% software.team_tags.each do |tag| %>
                <% if tag.name.present? %>
                  <div class="tag team-tag mb-2 bg-light rounded-pill shadow-sm">
                    <p class="px-3 py-1 m-0 small fw-bold"> <%= truncate(tag.name, length: 17, omission: '...') %> </p>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <p class="px-3 py-1 m-0 small text-muted">No tags</p>
            <% end %>
          </div>
        </div>

        <!-- Right Column: Content -->
        <div class="col-md-8 d-flex flex-column justify-content-between p-3" style="background-color: #ffffff;">
          <div>
            <div class="border-bottom mb-2">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h5 class="card-title mb-0 fw-bold">
                  <%= software.name %>
                </h5>
                <% if software.average_rating.present? %>
                  <span class="badge bg-info text-dark fs-6">
                    <%= software.average_rating %>
                    <i class="fa-solid fa-star"></i>
                  </span>
                <% else %>
                  <span class="badge bg-secondary fs-6">No ratings</span>
                <% end %>
              </div>

            </div>

            <p class="card-text text-muted mb-3"><%= truncate(software.description, length: 80, omission: '...') %></p>
          </div>

          <div>
            <% if software.category_tags.any? %>
              <div class="tag <%= software.category_tags.first.color %> me-2 mb-2 d-inline-block rounded-pill shadow-sm">
                <p class="px-3 py-1 m-0 small fw-bold"> <%= software.category_tags.first.name %> </p>
              </div>
            <% else %>
              <p class="text-muted small mb-2">No category</p>
            <% end %>

            <p class="card-text mb-0 fw-bold">
              <span class="text-success"><%= software.price_month.presence || "Free" %></span>
              <span class="text-muted small">/month</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>