config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :softwares do
    resources :licenses, only: %i[new create]
  end

  resources :licenses do
    resources :reviews, only: %i[new create]
  end

  resources :my_licenses, only: %i[index edit update]

  get 'my_profile', to: 'pages#profile'

  resources :my_softwares
end

app/controllers/my_softwares_controller.rb
class MySoftwaresController < ApplicationController
  before_action :authenticate_user!

  def index
    @my_softwares = Software.where(user_id: current_user.id)
    session[:mode] = "owner"
  end
end

app/views/my_softwares/_dashboard.html.erb
<% user_counts = @my_softwares.each_with_object(Hash.new(0)) do |mysoft, counts|%>
  <% counts[mysoft.name] += rand(1..4) %>
<% end %>

<% chart_data = user_counts.values.join(',') %>
<% chart_labels = user_counts.keys.join(',') %>

<div class="container mt-1">
  <div class="chart" data-controller="chart"
    data-chart-data="<%= chart_data %>"
    data-chart-labels="<%= chart_labels %>">
  </div>
</div>

app/views/my_softwares/index.html.erb
<div class="container mt-3">
  <div class="my-3">
    <div class="border-bottom m-4 pb-3">
      <div class="d-flex justify-content-between align-items-center">
        <h5 class="m-0">My softwares</h5>
        <%= link_to new_software_path, class: "btn btn-dark" do %>
          <i class="fa-solid fa-plus text-white me-2"></i>Add a new software
        <% end %>
      </div>
    </div>


    <div data-controller="dashboard">
      <div class="d-flex d-wrap align-content-center">
        <div class="green-button-visible" data-dashboard-target="dashboardButton">
          <h5 class="px-3 py-1 m-0" data-action="click->dashboard#viewDashboard"> Dashboard </h5>
        </div>

        <div class="black-button-disable text-center ms-5" data-dashboard-target="myAppsButton">
            <h5 class="px-3 py-1 m-0" data-action="click->dashboard#viewApps"> Apps posted </h5>
        </div>
      </div>


  <div data-dashboard-target="dashboard">
      <div class="row g-5 mt-1">
        <% if @my_softwares.present? %>
          <h4> Users per apps </h4>
          <%= render 'dashboard' %>
        <% else %>
          <p>You don't have posted an app yet ;)</p>
        <% end %>
      </div>
    </div>

      <div class="d-none" data-dashboard-target="myApps">
        <div class="row g-5 mt-3">
          <% @my_softwares.each do |software| %>
            <%= render 'shared/generic_soft_card', software: software %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>